<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Contracts\CompanyName.MyMeetings.Modules.UsersMI.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Refit" Version="8.0.0" />
	</ItemGroup>

</Project>