<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>  
		<ProjectReference Include="..\..\Infrastructure\CompanyName.MyMeetings.Modules.UserAccess.Infrastructure.csproj" />
	</ItemGroup>

</Project>
