<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<ItemGroup>
		<Folder Include="logs\" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="..\CompanyName.MyMeetings.Database\Scripts\Migrations\**" LinkBase="Scripts\Migrations">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Include="..\CompanyName.MyMeetings.Database\Scripts\Seeds\**" LinkBase="Scripts\Seeds">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>
</Project>